### ISSUE TITLE
Filter implementation

### ISSUE THREAD

**Issue by kobayash15** [DinocoCo/DinoGraph#3]
Real data, fusion table implemented, and graph visualization has been implemented, the filter that would specify the specific data sets has not been implemented yet, and requires work. Current program fits test 1 req., though filter's implementation should be completed as soon as possible.

**Comment by donaldsa18** [comment]
I gave up on trying to useGoogle's filter function and iterated through the entire dataset instead. It does not take much time to process and filter all of the data and it allows us to modify the data before displaying it. Closing ticket.
